version: '3.8'  # Specify the version of Docker Compose

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"  # Name of the container
    image: localstack/localstack  # Docker image to use
    ports:
      - "127.0.0.1:4566:4566"            # Map LocalStack Gateway port
   #   - "127.0.0.1:4510-4559:4510-4559" # Map external services port range
      - "127.0.0.1:8080:8080"            # Map UI port
    environment:
      - DEBUG=${DEBUG:-0}